language: node_js

node_js:
    - "4"
    - "6"

branches:
    only:
        - master

before_install: npm update -g npm

# travis runs 'npm install' by default, as the 'install' step

before_script: npm run dist;

# travis runs 'npm test' by default, as the 'script' step

# PLACEHOLDER FOR COVERAGE REPORTS ON GITHUB, IF WE WANT THEM.
# ALSO NEED TO ADD .coveralls.yml, IF WE WANT TO USE IT ON THE PRIVATE
# REPO.

after_script:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
    email:
        falcor@netflix.com

