dist: trusty
sudo: false
language: node_js
node_js:
    - "6"
before_install:
    - npm install -g npm@5
script:
    - npm test
    - npm run lint
notifications:
    email:
        falcor@netflix.com
